version: '3'

services:
  nodered:
    image: nodered/node-red
    container_name: nodered
    restart: always
    volumes:
      - ./volumes/node_red/data:/data
    ports:
      - "1880:1880" 

  influxdb:
    image: influxdb
    container_name: influxdb
    restart: always
    volumes:
      - ./volumes/influxdb/data:/var/lib/influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB="demo"
      - INFLUXDB_ADMIN_USER="admin"
      - INFLUXDB_ADMIN_PASSWORD="admin"

  chronograf:
    image: chronograf
    container_name: chronograf
    restart: always
    volumes:
      - ./volumes/chronograf/data:/var/lib/chronograf
    ports:
      - "8888:8888"
    depends_on: 
      - influxdb
